name: Publish Docker image to GHCR

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish (ex: v1.2.3). Required when running workflow manually."
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image name and tag
        id: meta
        env:
          REPO: ${{ github.repository }}
          REF: ${{ github.ref }}
          INPUT_TAG: ${{ github.event.inputs.tag }}
        run: |
          set -euo pipefail
          # ensure repository path is lowercase (ghcr requires lowercase names)
          REPO_LOWER=$(echo "${REPO}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LOWER}"
          TAG=""

          # Prefer explicit input (manual run). The input is required for manual runs.
          if [[ -n "${INPUT_TAG:-}" ]]; then
            TAG="${INPUT_TAG}"
          elif [[ "${REF}" == refs/tags/* ]]; then
            TAG=${REF#refs/tags/}
          else
            echo "No tag provided via workflow input and this is not a tag push. Aborting." >&2
            exit 1
          fi

          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          set -euo pipefail
          IMAGE=${{ steps.meta.outputs.image }}
          TAG=${{ steps.meta.outputs.tag }}
          echo "Building and pushing ${IMAGE}:${TAG}"
          docker buildx build --push -t ${IMAGE}:${TAG} -f ./Dockerfile .
